export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as RegistrationForm } from './RegistrationForm/RegistrationForm'
export { default as LoginForm } from './LoginForm/LoginForm'
export { default as ConfirmCodeModal } from './Modal/ConfirmCodeModal'
export { default as ForgetPasswordModal } from './Modal/ForgetPasswordModal'